services:
  postgres:
    user: root
    image: postgres:17.2-alpine
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_USER: ${POSTGRESQL_USER}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_PORT:-5432}:5432"
    restart: always  